dist: trusty

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "serhiikartashov"
    token:
      secure: $SONAR_TOKEN

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY_API
  app: java-project-template

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=searhiy_java-project-template

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
