dist: trusty
jdk:
  - openjdk11
script:
  - mvn clean install
  - mvn sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: $HEROKU_KEY_API
  app:
    master: java-project-template
#    dev: java-project-template-dev
#  run:
#    - "make db:migrate"
#    - restart